### ISSUE TITLE
torch geometric not found

### ISSUE THREAD

**Issue by BinhongLiu** [awfderry/COLLAPSE#7]
Hi, I prepared the environment with install_dependencies_cpu.sh in the Linux server. I found that the torch geometric could not be found, even though it was uninstalled and reinstalled.

the log is here:

(collapse) liuhongbin@slurm-master:~/soft/Pockets/COLLAPSE-main$ python search_site.py data/examples/1a0h.pdb B H363 data/datasets/pdb_embeddings.pkl --cutoff 1e-3 --verbose --num_iter 3
torch geometric not found, GNN examples will not work until it is.
Traceback (most recent call last):
  File "search_site.py", line 8, in <module>
    from collapse import atom_info, initialize_model, process_pdb, embed_residue
  File "/home/liuhongbin/soft/Pockets/COLLAPSE-main/collapse/__init__.py", line 1, in <module>
    from .data import process_pdb, initialize_model, embed_protein, embed_residue, embed_pocket
  File "/home/liuhongbin/soft/Pockets/COLLAPSE-main/collapse/data.py", line 21, in <module>
    from torch_geometric.data import Batch
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/liuhongbin/anaconda3/envs/collapse/lib/python3.8/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by awfderry** [comment]
This issue is caused by incompatibilities of PyG dependencies with Pytorch, and Cuda versions. It seems to be more common with older versions, so I updated the install scripts to the latest versions of all dependencies. Hopefully this makes installation less painful in the future
